# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
    paths:
      - setup.py
      - .github/workflows/python-package.yml
  pull_request:
    branches: [ master ]
    paths:
      - setup.py
      - .github/workflows/python-package.yml

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install flake8 pytest pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build binary wheel and a source tarball
      run: python3 setup.py sdist
    - name: Run lint
      run: pylint --rcfile=.pylintrc b2b_ai
    - name: Run tests
      run: python3 -m unittest b2b_ai
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
          password: ${{ secrets.pypi_password }}
          repository_url: https://test.pypi.org/legacy/
